name: Angular

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.15.0

    - name: Install dependencies
      run: npm install
